repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      args: ["--line-length=110"]
      language_version: python3.11

  - repo: local
    hooks:
    - id: isort
      name: isort
      entry: isort
      language: system
      types: [python]
      files: ^(backend/|tests/)
      exclude: ^backend/alembic/
      args: [
          '--line-length=110',
          '--multi-line=3',
          '--force-grid-wrap=0',
          '--trailing-comma',
          '--use-parentheses',
          '--ensure-newline-before-comments',
          '--profile=black',
          '--known-local-folder=digital_twin',
      ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        exclude: ^(backend/tests/|backend/alembic/)
        # TODO: This needs to be kept in sync with 
        # with requirements-dev.txt
        additional_dependencies: [
          alembic==1.10.4,
          types-beautifulsoup4==4.12.0.3, 
          types-html5lib==1.1.11.13, 
          types-oauthlib==3.2.0.9, 
          types-psycopg2==2.9.21.10, 
          types-python-dateutil==2.8.19.13, 
          types-regex==2023.3.23.1, 
          types-requests==2.28.11.17, 
          types-retry==0.9.9.3, 
          types-urllib3==1.26.25.11,
          types-redis==4.6.0.5,
        ]
        # TODO: add back once errors are addressed
        # args: [--strict]  
    