# fly.toml app configuration file generated for prosona-backend on 2023-07-10T18:59:37-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "prosona-backend-staging"
primary_region = "sjc"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  # The instance type for the VM
  vm_resources = "cpu2x"