import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { Analytics } from "@vercel/analytics/react";
import { Inter } from 'next/font/google';
import { cookies } from "next/headers";
import './css/style.css';

import { ToastProvider } from "../components/ui/Toast";
import AuthProvider from "../lib/auth/authProvider";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = async ({
  children,
}: {
  children: React.ReactNode;
}): Promise<JSX.Element> => {

  const supabase = createServerComponentClient({
    cookies,
  });

  const {
    data: { session },
  } = await supabase.auth.getSession();
  return (
    <html lang="en">
      <body className={`${inter.variable} font-inter antialiased bg-slate-900 text-slate-100 tracking-tight`}>
        <ToastProvider>
          <AuthProvider session={session}>
            <div className="flex flex-col min-h-screen overflow-hidden">
              {children}
            </div>
          </AuthProvider>
        </ToastProvider>
        <Analytics />
      </body>
    </html>
  )
}

export default RootLayout;
