"""add white listed email domain v2

Revision ID: 04e1399a8efe
Revises: 787cb0d36e38
Create Date: 2023-07-06 00:30:05.271883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e1399a8efe'
down_revision = '787cb0d36e38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
