"""add N-N

Revision ID: 171d48633315
Revises: 573433e7379e
Create Date: 2023-06-28 21:53:48.578670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171d48633315'
down_revision = '573433e7379e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('inviter_id', sa.UUID(), nullable=False),
    sa.Column('invitee_email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', name='invitationstatus', native_enum=False), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_organization_association',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('BASIC', 'ADMIN', name='userrole', native_enum=False), server_default='basic', nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'organization_id')
    )
    op.add_column('credential', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'credential', 'organizations', ['organization_id'], ['id'])
    op.add_column('slack_bots', sa.Column('prosona_organization_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'slack_bots', 'organizations', ['prosona_organization_id'], ['id'])
    op.add_column('slack_installations', sa.Column('prosona_organization_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'slack_installations', 'organizations', ['prosona_organization_id'], ['id'])
    op.add_column('slack_oauth_states', sa.Column('prosona_organization_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'slack_oauth_states', 'organizations', ['prosona_organization_id'], ['id'])
    op.add_column('slack_users', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'slack_users', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint('users_organization_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'role')
    op.drop_column('users', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    op.create_foreign_key('users_organization_id_fkey', 'users', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'slack_users', type_='foreignkey')
    op.drop_column('slack_users', 'organization_id')
    op.drop_constraint(None, 'slack_oauth_states', type_='foreignkey')
    op.drop_column('slack_oauth_states', 'prosona_organization_id')
    op.drop_constraint(None, 'slack_installations', type_='foreignkey')
    op.drop_column('slack_installations', 'prosona_organization_id')
    op.drop_constraint(None, 'slack_bots', type_='foreignkey')
    op.drop_column('slack_bots', 'prosona_organization_id')
    op.drop_constraint(None, 'credential', type_='foreignkey')
    op.drop_column('credential', 'organization_id')
    op.drop_table('user_organization_association')
    op.drop_table('invitations')
    # ### end Alembic commands ###
