"""make invitation id int

Revision ID: 17c50cef6e95
Revises: 3f0821d0ca3c
Create Date: 2023-07-11 23:17:59.989782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c50cef6e95'
down_revision = '3f0821d0ca3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_oauth_states', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'slack_oauth_states', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slack_oauth_states', type_='foreignkey')
    op.drop_column('slack_oauth_states', 'user_id')
    # ### end Alembic commands ###
