"""fix typo

Revision ID: 30b7fe6977cd
Revises: fda13acf44c9
Create Date: 2023-06-23 13:08:01.535024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30b7fe6977cd'
down_revision = 'fda13acf44c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slack_bots', 'enterprise_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('slack_bots', 'enterprise_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('slack_bots', 'team_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('slack_bots', 'bot_refresh_token',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('slack_bots', 'bot_token_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('slack_installations', 'enterprise_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('slack_installations', 'enterprise_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('slack_installations', 'enterprise_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('slack_installations', 'team_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('slack_installations', 'bot_token',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('slack_installations', 'bot_refresh_token',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('slack_installations', 'bot_token_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('slack_installations', 'user_token',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('slack_installations', 'user_scopes',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('slack_installations', 'user_refresh_token',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('slack_installations', 'user_token_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('slack_installations', 'incoming_webhook_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('slack_installations', 'incoming_webhook_channel',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('slack_installations', 'incoming_webhook_channel_id',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('slack_installations', 'incoming_webhook_configuration_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('slack_installations', 'token_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slack_installations', 'token_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('slack_installations', 'incoming_webhook_configuration_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('slack_installations', 'incoming_webhook_channel_id',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('slack_installations', 'incoming_webhook_channel',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('slack_installations', 'incoming_webhook_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('slack_installations', 'user_token_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('slack_installations', 'user_refresh_token',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('slack_installations', 'user_scopes',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('slack_installations', 'user_token',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('slack_installations', 'bot_token_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('slack_installations', 'bot_refresh_token',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('slack_installations', 'bot_token',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('slack_installations', 'team_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('slack_installations', 'enterprise_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('slack_installations', 'enterprise_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('slack_installations', 'enterprise_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('slack_bots', 'bot_token_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('slack_bots', 'bot_refresh_token',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('slack_bots', 'team_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('slack_bots', 'enterprise_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('slack_bots', 'enterprise_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###
