"""add new slack intergration v2

Revision ID: 3ff354bead41
Revises: a9c1e2ac6640
Create Date: 2023-07-25 16:38:00.160313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff354bead41'
down_revision = 'a9c1e2ac6640'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_oauth_states', sa.Column('slack_integration_type', sa.Enum('CONNECTOR', 'USER', name='slackintegration', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_oauth_states', 'slack_integration_type')
    # ### end Alembic commands ###
