"""fix typo

Revision ID: 40c16d96a101
Revises: 30b7fe6977cd
Create Date: 2023-06-23 14:35:02.500520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c16d96a101'
down_revision = '30b7fe6977cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
