"""make api_key and model_config org level

Revision ID: 4508ab899f2a
Revises: 40c16d96a101
Create Date: 2023-06-24 08:28:06.719515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4508ab899f2a'
down_revision = '40c16d96a101'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.drop_constraint('api_keys_user_id_fkey', 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'organizations', ['organization_id'], ['id'])
    op.drop_column('api_keys', 'user_id')
    op.add_column('model_configs', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.drop_constraint('model_configs_user_id_fkey', 'model_configs', type_='foreignkey')
    op.create_foreign_key(None, 'model_configs', 'organizations', ['organization_id'], ['id'])
    op.drop_column('model_configs', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_configs', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'model_configs', type_='foreignkey')
    op.create_foreign_key('model_configs_user_id_fkey', 'model_configs', 'users', ['user_id'], ['id'])
    op.drop_column('model_configs', 'organization_id')
    op.add_column('api_keys', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.create_foreign_key('api_keys_user_id_fkey', 'api_keys', 'users', ['user_id'], ['id'])
    op.drop_column('api_keys', 'organization_id')
    # ### end Alembic commands ###
