"""fix missing foreign key issue

Revision ID: 66cb56e13919
Revises: 9b46d6e7b18b
Create Date: 2023-06-23 12:01:46.807248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cb56e13919'
down_revision = '9b46d6e7b18b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connector', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'connector', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connector', type_='foreignkey')
    op.drop_column('connector', 'organization_id')
    # ### end Alembic commands ###
