"""add white listed email domain

Revision ID: 787cb0d36e38
Revises: 984ef0c0d759
Create Date: 2023-07-06 00:28:52.439422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787cb0d36e38'
down_revision = '984ef0c0d759'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('whitelisted_email_domain', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'whitelisted_email_domain')
    # ### end Alembic commands ###
