"""add user_id to connector for personal connector

Revision ID: 90c27498c973
Revises: efd1d7e12438
Create Date: 2023-07-29 23:53:38.232112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90c27498c973"
down_revision = "efd1d7e12438"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("connector", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "connector", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "connector", type_="foreignkey")
    op.drop_column("connector", "user_id")
    # ### end Alembic commands ###
