"""make invitation id int

Revision ID: a700adcd95f3
Revises: 04e1399a8efe
Create Date: 2023-07-06 21:57:22.539224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a700adcd95f3'
down_revision = '04e1399a8efe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
