"""make invitation id int

Revision ID: a96cc00ddb6b
Revises: a700adcd95f3
Create Date: 2023-07-06 22:00:14.523419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96cc00ddb6b'
down_revision = 'a700adcd95f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
