"""missing s for user

Revision ID: b2c1b69e582e
Revises: c2651e4454d8
Create Date: 2023-07-02 23:26:42.493518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c1b69e582e'
down_revision = 'c2651e4454d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
