"""add stuff

Revision ID: c2651e4454d8
Revises: 251c0915efba
Create Date: 2023-07-02 21:00:16.195713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2651e4454d8'
down_revision = '251c0915efba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
