"""add new slack_user_email

Revision ID: d8952687bbef
Revises: 39ab0114d859
Create Date: 2023-07-29 14:06:06.015999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d8952687bbef"
down_revision = "39ab0114d859"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("slack_users", sa.Column("slack_user_email", sa.String(), nullable=False))
    op.create_unique_constraint(
        "_team_id_slack_user_email_uc", "slack_users", ["team_id", "slack_user_email"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_team_id_slack_user_email_uc", "slack_users", type_="unique")
    op.drop_column("slack_users", "slack_user_email")
    # ### end Alembic commands ###
