"""add prosona_user_id

Revision ID: e5d74b4066f2
Revises: 17c50cef6e95
Create Date: 2023-07-11 23:20:43.559822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d74b4066f2'
down_revision = '17c50cef6e95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_oauth_states', sa.Column('prosona_user_id', sa.UUID(), nullable=False))
    op.drop_constraint('slack_oauth_states_user_id_fkey', 'slack_oauth_states', type_='foreignkey')
    op.create_foreign_key(None, 'slack_oauth_states', 'users', ['prosona_user_id'], ['id'])
    op.drop_column('slack_oauth_states', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_oauth_states', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'slack_oauth_states', type_='foreignkey')
    op.create_foreign_key('slack_oauth_states_user_id_fkey', 'slack_oauth_states', 'users', ['user_id'], ['id'])
    op.drop_column('slack_oauth_states', 'prosona_user_id')
    # ### end Alembic commands ###
