"""add slack names

Revision ID: efd1d7e12438
Revises: d8952687bbef
Create Date: 2023-07-29 22:01:13.129735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd1d7e12438'
down_revision = 'd8952687bbef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_organization_associations', sa.Column('team_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_organization_associations', 'team_name')
    # ### end Alembic commands ###
