"""remove api_key

Revision ID: faa8fd8f51a3
Revises: 4508ab899f2a
Create Date: 2023-06-24 23:58:56.787342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'faa8fd8f51a3'
down_revision = '4508ab899f2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_configs')
    op.drop_table('api_keys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key_type', postgresql.ENUM('ANTHROPHIC_API_KEY', 'OPENAI_API_KEY', 'SLACK_BOT_KEY', name='dbapikeytype'), autoincrement=False, nullable=False),
    sa.Column('key_value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='api_keys_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='api_keys_pkey')
    )
    op.create_table('model_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supported_model_enum', postgresql.ENUM('GPT3_5', 'GPT4', 'ANTHROPIC', name='dbsupportedmodeltype'), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='model_configs_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='model_configs_pkey')
    )
    # ### end Alembic commands ###
