"""fix typo

Revision ID: fda13acf44c9
Revises: 66cb56e13919
Create Date: 2023-06-23 12:06:58.099339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda13acf44c9'
down_revision = '66cb56e13919'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
