version: '3'
services:
  api_server:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
  background:
    build:
      context: ../backend
      dockerfile: Dockerfile.background
    restart: always
    env_file:
      - .env
  web_server:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    depends_on:
      - api_server
    restart: always
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://api_server:8080
  nginx:
    image: nginx:1.23.4-alpine
    restart: always
    depends_on:
      - api_server
      - web_server
    environment:
      - DOMAIN=localhost
    ports:
      - "80:80"
      - "3000:80"  # allow for localhost:3000 usage, since that is the norm
    volumes:
      - ../data/nginx:/etc/nginx/conf.d
    command: > 
      /bin/sh -c "envsubst '$$\{DOMAIN\}' < /etc/nginx/conf.d/app.conf.template.dev > /etc/nginx/conf.d/app.conf 
      && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\""
