name: airplane

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout only backend directory
        uses: actions/checkout@v2
        with:
          path: backend

      - uses: airplanedev/airplane-deploy@v1
        with:
          api-key: ${{ secrets.AIRPLANE_API_KEY }}
          team-id: tea20230712zqy23sar9zu
          task-directory: ./backend
